@export()
@description('Private Endpoint Private DNS zone keys supported by the dns library: naming-style resource type keys, with a `_<group>` suffix for resource types that require several zones (for example `storage_account_blob`); zone names follow the Microsoft Learn private endpoint DNS configuration appendix (https://learn.microsoft.com/azure/private-link/private-endpoint-dns). Generated by scripts/generate_dns.py.')
type privateDnsZoneKey = 'database_account'
  | 'database_account_cassandra'
  | 'database_account_gremlin'
  | 'database_account_mongo'
  | 'database_account_table'
  | 'db_for_my_sql_server'
  | 'db_for_postgre_sql_server'
  | 'event_hub_namespace'
  | 'factory'
  | 'key_vault_vault'
  | 'redis'
  | 'registry'
  | 'service_bus_namespace'
  | 'site_slot'
  | 'site_web_app'
  | 'sql_server'
  | 'storage_account_blob'
  | 'storage_account_dfs'
  | 'storage_account_file'
  | 'storage_account_queue'
  | 'storage_account_table'

@export()
@description('Private DNS zone name per zone key (for example `storage_account_blob` -> `privatelink.blob.core.windows.net`). Zone names follow the Microsoft Learn private endpoint DNS configuration appendix (https://learn.microsoft.com/azure/private-link/private-endpoint-dns). Generated by scripts/generate_dns.py.')
var privateDnsZoneMap = {
  database_account: 'privatelink.documents.azure.com'
  database_account_cassandra: 'privatelink.cassandra.cosmos.azure.com'
  database_account_gremlin: 'privatelink.gremlin.cosmos.azure.com'
  database_account_mongo: 'privatelink.mongo.cosmos.azure.com'
  database_account_table: 'privatelink.table.cosmos.azure.com'
  db_for_my_sql_server: 'privatelink.mysql.database.azure.com'
  db_for_postgre_sql_server: 'privatelink.postgres.database.azure.com'
  event_hub_namespace: 'privatelink.servicebus.windows.net'
  factory: 'privatelink.datafactory.azure.net'
  key_vault_vault: 'privatelink.vaultcore.azure.net'
  redis: 'privatelink.redis.cache.windows.net'
  registry: 'privatelink.azurecr.io'
  service_bus_namespace: 'privatelink.servicebus.windows.net'
  site_slot: 'privatelink.azurewebsites.net'
  site_web_app: 'privatelink.azurewebsites.net'
  #disable-next-line no-hardcoded-env-urls
  sql_server: 'privatelink.database.windows.net'
  #disable-next-line no-hardcoded-env-urls
  storage_account_blob: 'privatelink.blob.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
  storage_account_dfs: 'privatelink.dfs.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
  storage_account_file: 'privatelink.file.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
  storage_account_queue: 'privatelink.queue.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
  storage_account_table: 'privatelink.table.core.windows.net'
}

@export()
@description('All Private DNS zones per naming-style resource type key (for example `storage_account` -> the blob, dfs, file, queue and table zones). Zone names follow the Microsoft Learn private endpoint DNS configuration appendix (https://learn.microsoft.com/azure/private-link/private-endpoint-dns). Generated by scripts/generate_dns.py.')
var privateDnsZonesByType = {
  database_account: [
    'privatelink.documents.azure.com'
    'privatelink.cassandra.cosmos.azure.com'
    'privatelink.gremlin.cosmos.azure.com'
    'privatelink.mongo.cosmos.azure.com'
    'privatelink.table.cosmos.azure.com'
  ]
  db_for_my_sql_server: [
    'privatelink.mysql.database.azure.com'
  ]
  db_for_postgre_sql_server: [
    'privatelink.postgres.database.azure.com'
  ]
  event_hub_namespace: [
    'privatelink.servicebus.windows.net'
  ]
  factory: [
    'privatelink.datafactory.azure.net'
  ]
  key_vault_vault: [
    'privatelink.vaultcore.azure.net'
  ]
  redis: [
    'privatelink.redis.cache.windows.net'
  ]
  registry: [
    'privatelink.azurecr.io'
  ]
  service_bus_namespace: [
    'privatelink.servicebus.windows.net'
  ]
  site_slot: [
    'privatelink.azurewebsites.net'
  ]
  site_web_app: [
    'privatelink.azurewebsites.net'
  ]
  sql_server: [
  #disable-next-line no-hardcoded-env-urls
    'privatelink.database.windows.net'
  ]
  storage_account: [
  #disable-next-line no-hardcoded-env-urls
    'privatelink.blob.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
    'privatelink.dfs.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
    'privatelink.file.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
    'privatelink.queue.core.windows.net'
  #disable-next-line no-hardcoded-env-urls
    'privatelink.table.core.windows.net'
  ]
}
