#!/usr/bin/env python3
"""Regenerates the regions module's curated data files:

- modules/regions/regions-info.bicep - Azure paired regions and geographies,
  keyed by the region abbreviations from regions-data.bicep
- modules/regions/regions-info.md     - paired region and geography catalogue

The PAIRED_REGIONS and GEOGRAPHIES tables below are CURATED BY HAND: the
abbreviation source has no machine-readable paired-region or geography data.
Reviewers must spot-check the curated tables against the cited pages; this
curation is the module's main accuracy risk.

Sources:
- Microsoft Learn, Azure paired regions (cross-region replication in Azure)
  https://learn.microsoft.com/azure/reliability/cross-region-replication-azure
  Global Azure pairs follow that page's table. China region pairs follow the
  in-country pairing of the 21Vianet-operated regions and are not listed there.
- Microsoft, Azure geographies (the geography groups of the Azure region
  metadata, for example 'Europe' and 'North America')
  https://azure.microsoft.com/explore/global-infrastructure/geographies/
- Region abbreviations and AZ CLI names come from the claranet region naming
  standard via scripts/generate.py
  https://github.com/claranet/terraform-azurerm-regions

modules/regions/regions.bicep (the region functions) and
modules/regions/README.md (the API and usage docs) are hand-written and are
NOT generated by this script; regions.bicep imports the generated data.

Run from the repository root: python3 scripts/generate_regions.py
"""
import os

import generate

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = os.path.join(REPO, 'modules', 'regions')

# Continental/country aggregates in the abbreviation data: not real regions,
# so they have no pair and no geography.
AGGREGATES = {
    'asiapacific', 'australia', 'brazil', 'canada', 'europe', 'india',
    'japan', 'korea', 'newzealand', 'norway', 'singapore', 'sweden',
    'unitedstates',
}

GEOGRAPHY_NAMES = {
    'Africa', 'Asia Pacific', 'Australia', 'Europe', 'Middle East',
    'North America', 'South America',
}

# AZ CLI name -> AZ CLI name of the Azure paired region, '' when the region
# has no pair. Curated against Microsoft Learn "Azure paired regions".
PAIRED_REGIONS = {
    'australiacentral': 'australiacentral2',
    'australiacentral2': 'australiacentral',
    'australiaeast': 'australiasoutheast',
    'australiasoutheast': 'australiaeast',
    'brazilsouth': 'southcentralus',
    'brazilsoutheast': 'brazilsouth',
    'canadacentral': 'canadaeast',
    'canadaeast': 'canadacentral',
    'centralindia': 'southindia',
    'southindia': 'centralindia',
    'westindia': 'southindia',
    'centralus': 'eastus2',
    'eastus': 'westus',
    'eastus2': 'centralus',
    'northcentralus': 'southcentralus',
    'southcentralus': 'northcentralus',
    'westcentralus': 'westus2',
    'westus': 'eastus',
    'westus2': 'westcentralus',
    'westus3': 'eastus',
    'chinaeast': 'chinanorth',
    'chinanorth': 'chinaeast',
    'chinaeast2': 'chinanorth2',
    'chinanorth2': 'chinaeast2',
    'chinaeast3': 'chinanorth3',
    'chinanorth3': 'chinaeast3',
    'eastasia': 'southeastasia',
    'southeastasia': 'eastasia',
    'francecentral': 'francesouth',
    'francesouth': 'francecentral',
    'germanycentral': '',
    'germanynorth': 'germanywestcentral',
    'germanynortheast': '',
    'germanywestcentral': 'germanynorth',
    'israelcentral': '',
    'italynorth': '',
    'japaneast': 'japanwest',
    'japanwest': 'japaneast',
    'koreacentral': 'koreasouth',
    'koreasouth': 'koreacentral',
    'newzealandnorth': '',
    'northeurope': 'westeurope',
    'westeurope': 'northeurope',
    'norwayeast': 'norwaywest',
    'norwaywest': 'norwayeast',
    'polandcentral': '',
    'qatarcentral': '',
    'southafricanorth': 'southafricawest',
    'southafricawest': 'southafricanorth',
    'swedencentral': 'swedensouth',
    'swedensouth': 'swedencentral',
    'switzerlandnorth': 'switzerlandwest',
    'switzerlandwest': 'switzerlandnorth',
    'uaecentral': 'uaenorth',
    'uaenorth': 'uaecentral',
    'uksouth': 'ukwest',
    'ukwest': 'uksouth',
}

# AZ CLI name -> Azure geography of the region. Curated against the Azure
# geographies taxonomy of the Azure region metadata.
GEOGRAPHIES = {
    'australiacentral': 'Australia',
    'australiacentral2': 'Australia',
    'australiaeast': 'Australia',
    'australiasoutheast': 'Australia',
    'brazilsouth': 'South America',
    'brazilsoutheast': 'South America',
    'canadacentral': 'North America',
    'canadaeast': 'North America',
    'centralindia': 'Asia Pacific',
    'southindia': 'Asia Pacific',
    'westindia': 'Asia Pacific',
    'centralus': 'North America',
    'eastus': 'North America',
    'eastus2': 'North America',
    'northcentralus': 'North America',
    'southcentralus': 'North America',
    'westcentralus': 'North America',
    'westus': 'North America',
    'westus2': 'North America',
    'westus3': 'North America',
    'chinaeast': 'Asia Pacific',
    'chinanorth': 'Asia Pacific',
    'chinaeast2': 'Asia Pacific',
    'chinanorth2': 'Asia Pacific',
    'chinaeast3': 'Asia Pacific',
    'chinanorth3': 'Asia Pacific',
    'eastasia': 'Asia Pacific',
    'southeastasia': 'Asia Pacific',
    'francecentral': 'Europe',
    'francesouth': 'Europe',
    'germanycentral': 'Europe',
    'germanynorth': 'Europe',
    'germanynortheast': 'Europe',
    'germanywestcentral': 'Europe',
    'israelcentral': 'Middle East',
    'italynorth': 'Europe',
    'japaneast': 'Asia Pacific',
    'japanwest': 'Asia Pacific',
    'koreacentral': 'Asia Pacific',
    'koreasouth': 'Asia Pacific',
    'newzealandnorth': 'Asia Pacific',
    'northeurope': 'Europe',
    'westeurope': 'Europe',
    'norwayeast': 'Europe',
    'norwaywest': 'Europe',
    'polandcentral': 'Europe',
    'qatarcentral': 'Middle East',
    'southafricanorth': 'Africa',
    'southafricawest': 'Africa',
    'swedencentral': 'Europe',
    'swedensouth': 'Europe',
    'switzerlandnorth': 'Europe',
    'switzerlandwest': 'Europe',
    'uaecentral': 'Middle East',
    'uaenorth': 'Middle East',
    'uksouth': 'Europe',
    'ukwest': 'Europe',
}


def curate(region_rows):
    """Join the curated tables with the abbreviation data, returning a row
    (display, cli, short, paired, geography) per real region, sorted by
    display name."""
    real = {}
    for display, cli, short, _ in region_rows:
        if cli in AGGREGATES:
            continue
        for table, name in ((PAIRED_REGIONS, 'PAIRED_REGIONS'), (GEOGRAPHIES, 'GEOGRAPHIES')):
            if cli not in table:
                raise SystemExit(f'no curated {name} entry for region {cli} ({display}); '
                                 f'curate it or add it to AGGREGATES')
        real[cli] = (display, short)
    rows = []
    for cli, (display, short) in sorted(real.items(), key=lambda kv: kv[1][0]):
        paired = PAIRED_REGIONS[cli]
        if paired and paired not in real:
            raise SystemExit(f'paired region {paired!r} of {cli} is not a known region')
        geography = GEOGRAPHIES[cli]
        if geography not in GEOGRAPHY_NAMES:
            raise SystemExit(f'unknown geography {geography!r} for region {cli}')
        rows.append((display, cli, short, paired, geography))
    return rows


def emit_regions_info(rows):
    lines = [
        '@export()',
        "@description('Azure paired regions, keyed by the region abbreviation that regionCode() resolves to; values are the AZ CLI name of the paired Azure region (for example uks -> ukwest). Regions without a pair and non-region aggregates are absent. Curated by hand against Microsoft Learn `Azure paired regions` (https://learn.microsoft.com/azure/reliability/cross-region-replication-azure); China region pairs follow the in-country pairing of the 21Vianet-operated regions and are not listed there. Generated by scripts/generate_regions.py - spot-check the curated tables when reviewing.')",
        'var regionPairs = {',
    ]
    for display, cli, short, paired, geography in rows:
        lines.append(f"  {generate.bicep_key(short)}: '{paired}'")
    lines += [
        '}',
        '',
        '@export()',
        "@description('Azure geographies, keyed by the region abbreviation that regionCode() resolves to; values are the geography the region belongs to (for example uks -> Europe). Non-region aggregates are absent. Curated by hand against the Azure geographies taxonomy of the Azure region metadata (https://azure.microsoft.com/explore/global-infrastructure/geographies/). Generated by scripts/generate_regions.py - spot-check the curated tables when reviewing.')",
        'var regionGeographies = {',
    ]
    for display, cli, short, paired, geography in rows:
        lines.append(f"  {generate.bicep_key(short)}: '{geography}'")
    lines.append('}')
    return '\n'.join(lines) + '\n'


def emit_regions_info_md(rows):
    table = '\n'.join(
        f'| {display} | `{cli}` | `{short}` | {f"`{paired}`" if paired else "&mdash;"} | {geography} |'
        for display, cli, short, paired, geography in rows)
    return f'''# Region pairs and geographies

Azure paired regions and geographies, curated by hand in
`scripts/generate_regions.py` (the abbreviation source has no machine-readable
paired-region or geography data) - spot-check against the cited pages when
reviewing changes. Paired regions follow
[Microsoft Learn, Azure paired regions](https://learn.microsoft.com/azure/reliability/cross-region-replication-azure);
China region pairs follow the in-country pairing of the 21Vianet-operated
regions and are not listed on that page. Geographies follow the
[Azure geographies](https://azure.microsoft.com/explore/global-infrastructure/geographies/)
taxonomy of the Azure region metadata.

| Region | AZ CLI name | Abbreviation | Paired region | Geography |
|---|---|---|---|---|
{table}
'''


def main():
    _, region_rows = generate.load_regions()
    rows = curate(region_rows)
    with open(os.path.join(MODULE, 'regions-info.bicep'), 'w') as f:
        f.write(emit_regions_info(rows))
    with open(os.path.join(MODULE, 'regions-info.md'), 'w') as f:
        f.write(emit_regions_info_md(rows))
    print(f'emitted modules/regions/regions-info.bicep and regions-info.md '
          f'({len(rows)} curated regions)')


if __name__ == '__main__':
    main()
