#!/usr/bin/env python3
"""Regenerates the naming and regions modules' generated files from upstream
naming standards:

- modules/naming/rules.bicep         - resource type keys and per-type naming rules
- modules/naming/resource-types.md   - resource type catalogue
- modules/regions/regions-data.bicep - Azure region abbreviations
- modules/regions/regions.md         - region abbreviation catalogue

modules/naming/naming.bicep (the functions and the namingContext type),
modules/regions/regions.bicep (the region functions) and both modules'
README.md files (the API and usage docs) are hand-written and are NOT
generated by this script; the modules import the generated data. The regions
module's curated paired-region and geography data is generated by
scripts/generate_regions.py.

Sources:
- Microsoft Azure Verified Naming Utility resource-name-rules (per-type slug,
  length, hyphen and casing rules)
  https://github.com/Azure/terraform-azure-avm-utl-naming
- claranet/terraform-azurerm-regions (region abbreviation standard)
  https://github.com/claranet/terraform-azurerm-regions

Run from the repository root: python3 scripts/generate.py
"""
import json
import os
import re
import urllib.request

AVM_BASE = 'https://raw.githubusercontent.com/Azure/terraform-azure-avm-utl-naming/main/data/'
REGIONS_URL = 'https://raw.githubusercontent.com/claranet/terraform-azurerm-regions/master/regions.tf'

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = os.path.join(REPO, 'modules', 'naming')
REGIONS_MODULE = os.path.join(REPO, 'modules', 'regions')

IDENT = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


def bicep_key(k):
    return k if IDENT.match(k) else f"'{k}'"


def distill_rules():
    generated = json.loads(fetch(AVM_BASE + 'resource-name-rules.json'))['resources']
    manual = json.loads(fetch(AVM_BASE + 'resource-name-rules.manual.json')).get('resources') or {}
    resources = dict(generated)
    for k, v in manual.items():
        resources[k] = {**resources.get(k, {}), **v}
    out = {}
    for key, r in sorted(resources.items()):
        if not r.get('slug'):
            continue
        out[key] = {
            'slug': r['slug'],
            'resourceType': r.get('resource_type'),
            'max': r.get('max_length'),
            'dashes': bool(r.get('dashes')),
            'lowercase': bool(r.get('lowercase')),
        }
    return out


def parse_locals(tf):
    """Parse HCL locals blocks of the form `  name = { key = "value" ... }`."""
    blocks = {}
    for m in re.finditer(r'^  (\w+) = \{\n(.*?)^  \}', tf, re.M | re.S):
        body = m.group(2)
        entries = re.findall(r'^\s*"?\(?([\w -]+?)\)?"?\s*=\s*"([^"]*)"\s*(?:#.*)?$', body, re.M)
        blocks[m.group(1)] = {k.strip(): v for k, v in entries}
    return blocks


def load_regions():
    blocks = parse_locals(fetch(REGIONS_URL))
    regions, short, cli = blocks['regions'], blocks['short_names'], blocks['cli_names']
    paired = blocks.get('paired', {})
    codes = {}
    rows = []
    for slug, display in regions.items():
        if slug not in short or slug not in cli or cli[slug] == slug:
            continue  # skip continental aggregates, keep real regions only
        s = short[slug]
        codes[cli[slug].lower()] = s
        codes[slug] = s
        codes[re.sub(r'\s+', '-', display.lower())] = s
        p = paired.get(slug)
        rows.append((display, cli[slug], s, short.get(p, p) if p else ''))
    return codes, rows


def emit_rules(rules):
    keys = sorted(rules)
    lines = [
        '@export()',
        "@description('Resource type identifiers supported by the naming library. Keys follow the Azure Verified Naming Utility resource catalog (https://github.com/Azure/terraform-azure-avm-utl-naming); abbreviations follow the Cloud Adoption Framework recommendations (https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) as catalogued by the Azure Periodic Table (azureperiodictable.com); length, separator and case rules follow the Azure resource naming rules (https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules). Generated by scripts/generate.py.')",
        'type resourceType = ' + f"'{keys[0]}'",
    ]
    for k in keys[1:]:
        lines.append(f"  | '{k}'")
    lines += [
        '',
        '@export()',
        "@description('Naming rules per resource type: `slug` is the Cloud Adoption Framework abbreviation, `max` the maximum allowed name length, `dashes` whether hyphens are allowed in the name, `lowercase` whether the name must be lower case. Rules sourced from the Azure Verified Naming Utility catalog (https://github.com/Azure/terraform-azure-avm-utl-naming) and the Azure resource naming rules (https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules). Generated by scripts/generate.py.')",
        'var nameRules = {',
    ]
    for k in keys:
        r = rules[k]
        lines += [
            f'  {bicep_key(k)}: {{',
            f"    slug: '{r['slug']}'",
        ]
        if r['max'] is not None:
            lines.append(f"    max: {r['max']}")
        lines += [
            f'    dashes: {str(r["dashes"]).lower()}',
            f'    lowercase: {str(r["lowercase"]).lower()}',
            '  }',
        ]
    lines.append('}')
    return '\n'.join(lines) + '\n'


def emit_regions(region_codes):
    lines = [
        '@export()',
        "@description('Azure region abbreviations following the claranet region naming standard (https://github.com/claranet/terraform-azurerm-regions). Lookup keys accept the AZ CLI name (`uksouth`), the dashed form (`uk-south`) and the display name (`UK South`), all case insensitive; values are the short notation used as the region segment of resource names. Generated by scripts/generate.py.')",
        'var regionCodes = {',
    ]
    for k in sorted(region_codes):
        lines.append(f"  {bicep_key(k)}: '{region_codes[k]}'")
    lines.append('}')
    return '\n'.join(lines) + '\n'


def emit_resource_types_md(rules):
    keys = sorted(rules)
    rows = '\n'.join(
        f"| `{k}` | {rules[k]['resourceType'] or ''} | `{rules[k]['slug']}` | "
        f"{rules[k]['max'] if rules[k]['max'] is not None else '&mdash;'} | "
        f"{'yes' if rules[k]['dashes'] else 'no'} | {'yes' if rules[k]['lowercase'] else 'no'} |"
        for k in keys)
    return f'''# Supported resource types

Type keys for the naming functions, with the Cloud Adoption Framework
abbreviation and the per-type naming rules used to compose compliant names.
Sourced from the [Azure Verified Naming Utility](https://github.com/Azure/terraform-azure-avm-utl-naming)
catalog and the [Azure resource naming rules](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules).

| Type key | ARM resource type | Abbreviation | Max length | Hyphens | Lower case |
|---|---|---|---|---|---|
{rows}
'''


def emit_regions_md(region_rows):
    rows = '\n'.join(
        f'| {display} | `{cli}` | `{short}` | {paired} |' for display, cli, short, paired in region_rows)
    return f'''# Region abbreviations

Azure region abbreviations following the
[claranet region naming standard](https://github.com/claranet/terraform-azurerm-regions).
The region functions accept the AZ CLI name, the dashed form or the display
name (for example `uksouth`, `uk-south` or `UK South`), all case insensitive.

| Region | AZ CLI name | Abbreviation | Paired region |
|---|---|---|---|
{rows}
'''


def main():
    rules = distill_rules()
    region_codes, region_rows = load_regions()
    print(f'{len(rules)} resource types, {len(region_codes)} region lookup keys, {len(region_rows)} regions')
    with open(os.path.join(MODULE, 'rules.bicep'), 'w') as f:
        f.write(emit_rules(rules))
    with open(os.path.join(REGIONS_MODULE, 'regions-data.bicep'), 'w') as f:
        f.write(emit_regions(region_codes))
    with open(os.path.join(MODULE, 'resource-types.md'), 'w') as f:
        f.write(emit_resource_types_md(rules))
    with open(os.path.join(REGIONS_MODULE, 'regions.md'), 'w') as f:
        f.write(emit_regions_md(region_rows))
    print('emitted modules/naming/rules.bicep, resource-types.md and '
          'modules/regions/regions-data.bicep, regions.md')


if __name__ == '__main__':
    main()
