#!/usr/bin/env python3
"""Regenerates the dns module's generated files:

- modules/dns/zones.bicep  - private DNS zone keys and zone map
- modules/dns/zones.md     - private DNS zone catalogue

modules/dns/dns.bicep (the lookup functions) and modules/dns/README.md
(the API and usage docs) are hand-written and are NOT generated by this
script; dns.bicep imports the generated data.

The mapping from naming-style resource type keys (the same keys the naming
module uses) to Private Endpoint Private DNS zones is curated below: no
upstream list carries the key mapping itself. The script first attempts to
fetch the Microsoft Learn "Private endpoint DNS configuration" appendix and
cross-checks every curated zone name against it, warning about any zone
the page does not list. If the fetch fails or the page looks restructured
(too few zones found), the script falls back to the curated data alone and
warns. Either way the emitted files are identical and built from the
curated dict only, so regeneration is deterministic.

Sources:
- Microsoft Learn, Azure Private Endpoint DNS configuration (zone names)
  https://learn.microsoft.com/azure/private-link/private-endpoint-dns
- keys aligned with the naming module's resource type keys
  (modules/naming/rules.bicep)

Run from the repository root: python3 scripts/generate_dns.py
"""
import os
import re
import urllib.request

LEARN_URL = 'https://learn.microsoft.com/en-us/azure/private-link/private-endpoint-dns'
ZONE_RE = re.compile(r'privatelink\.[a-z0-9.-]+')
MIN_UPSTREAM_ZONES = 20  # below this the fetched page looks restructured, not a usable source

# Curated mapping: naming-style resource type key -> ARM resource type plus
# its Private Endpoint zones. Each entry is a (group, zone) pair; a None group
# means the type has a single zone and its key is the type key itself, a
# named group flattens to the '<type>_<group>' zone key.
CURATED = {
    'storage_account': {
        'arm': 'Microsoft.Storage/storageAccounts',
        'groups': [
            ('blob', 'privatelink.blob.core.windows.net'),
            ('dfs', 'privatelink.dfs.core.windows.net'),
            ('file', 'privatelink.file.core.windows.net'),
            ('queue', 'privatelink.queue.core.windows.net'),
            ('table', 'privatelink.table.core.windows.net'),
        ],
    },
    'key_vault_vault': {
        'arm': 'Microsoft.KeyVault/vaults',
        'groups': [(None, 'privatelink.vaultcore.azure.net')],
    },
    'sql_server': {
        'arm': 'Microsoft.Sql/servers',
        'groups': [(None, 'privatelink.database.windows.net')],
    },
    'db_for_postgre_sql_server': {
        'arm': 'Microsoft.DBforPostgreSQL/servers',
        'groups': [(None, 'privatelink.postgres.database.azure.com')],
    },
    'db_for_my_sql_server': {
        'arm': 'Microsoft.DBforMySQL/servers',
        'groups': [(None, 'privatelink.mysql.database.azure.com')],
    },
    'event_hub_namespace': {
        'arm': 'Microsoft.EventHub/namespaces',
        'groups': [(None, 'privatelink.servicebus.windows.net')],
    },
    'service_bus_namespace': {
        'arm': 'Microsoft.ServiceBus/namespaces',
        'groups': [(None, 'privatelink.servicebus.windows.net')],
    },
    'registry': {
        'arm': 'Microsoft.ContainerRegistry/registries',
        'groups': [(None, 'privatelink.azurecr.io')],
    },
    'database_account': {
        'arm': 'Microsoft.DocumentDB/databaseAccounts',
        'groups': [
            (None, 'privatelink.documents.azure.com'),
            ('cassandra', 'privatelink.cassandra.cosmos.azure.com'),
            ('gremlin', 'privatelink.gremlin.cosmos.azure.com'),
            ('mongo', 'privatelink.mongo.cosmos.azure.com'),
            ('table', 'privatelink.table.cosmos.azure.com'),
        ],
    },
    'site_web_app': {
        'arm': 'Microsoft.Web/sites',
        'groups': [(None, 'privatelink.azurewebsites.net')],
    },
    'site_slot': {
        'arm': 'Microsoft.Web/sites/slots',
        'groups': [(None, 'privatelink.azurewebsites.net')],
    },
    'redis': {
        'arm': 'Microsoft.Cache/Redis',
        'groups': [(None, 'privatelink.redis.cache.windows.net')],
    },
    'factory': {
        'arm': 'Microsoft.DataFactory/factories',
        'groups': [(None, 'privatelink.datafactory.azure.net')],
    },
}

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = os.path.join(REPO, 'modules', 'dns')

IDENT = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')

# Hosts the Bicep linter's no-hardcoded-env-urls rule flags; the zone names are
# Private DNS zone names, not environment endpoints, so those lines carry a
# disable pragma instead.
LINTED_HOSTS = ('database.windows.net', 'core.windows.net')


def bicep_key(k):
    return k if IDENT.match(k) else f"'{k}'"


def zone_line(indent, key, zone):
    prefix = f'  #disable-next-line no-hardcoded-env-urls\n{indent}' if zone.endswith(LINTED_HOSTS) else indent
    return f"{prefix}{key}: '{zone}'"


def zone_value_line(indent, zone):
    if zone.endswith(LINTED_HOSTS):
        return f"  #disable-next-line no-hardcoded-env-urls\n{indent}'{zone}'"
    return f"{indent}'{zone}'"


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


def upstream_zones():
    """Fetch the Learn appendix zone names, or None when unusable."""
    try:
        zones = set(ZONE_RE.findall(fetch(LEARN_URL).lower()))
    except Exception as e:
        print(f'WARNING: could not fetch {LEARN_URL} ({e}); using curated data only')
        return None
    if len(zones) < MIN_UPSTREAM_ZONES:
        print(f'WARNING: fetched page lists only {len(zones)} zones; looks restructured, using curated data only')
        return None
    return zones


def zone_key(type_key, group):
    return type_key if group is None else f'{type_key}_{group}'


def check_against_upstream(zones, upstream):
    if upstream is None:
        return
    for zone in sorted(zones):
        if zone not in upstream:
            print(f'WARNING: {zone} is not listed in the Learn DNS configuration appendix; check it')


def emit_zones(zone_keys, zone_map, zones_by_type):
    lines = [
        '@export()',
        "@description('Private Endpoint Private DNS zone keys supported by the dns library: naming-style resource type keys, with a `_<group>` suffix for resource types that require several zones (for example `storage_account_blob`); zone names follow the Microsoft Learn private endpoint DNS configuration appendix (https://learn.microsoft.com/azure/private-link/private-endpoint-dns). Generated by scripts/generate_dns.py.')",
        'type privateDnsZoneKey = ' + f"'{zone_keys[0]}'",
    ]
    for k in zone_keys[1:]:
        lines.append(f"  | '{k}'")
    lines += [
        '',
        '@export()',
        "@description('Private DNS zone name per zone key (for example `storage_account_blob` -> `privatelink.blob.core.windows.net`). Zone names follow the Microsoft Learn private endpoint DNS configuration appendix (https://learn.microsoft.com/azure/private-link/private-endpoint-dns). Generated by scripts/generate_dns.py.')",
        'var privateDnsZoneMap = {',
    ]
    for k in zone_keys:
        lines.append(zone_line('  ', bicep_key(k), zone_map[k]))
    lines += [
        '}',
        '',
        '@export()',
        "@description('All Private DNS zones per naming-style resource type key (for example `storage_account` -> the blob, dfs, file, queue and table zones). Zone names follow the Microsoft Learn private endpoint DNS configuration appendix (https://learn.microsoft.com/azure/private-link/private-endpoint-dns). Generated by scripts/generate_dns.py.')",
        'var privateDnsZonesByType = {',
    ]
    for t in sorted(zones_by_type):
        lines.append(f'  {bicep_key(t)}: [')
        for zone in zones_by_type[t]:
            lines.append(zone_value_line('    ', zone))
        lines.append('  ]')
    lines.append('}')
    return '\n'.join(lines) + '\n'


def emit_zones_md(curated):
    rows = '\n'.join(
        f"| `{t}` | `{curated[t]['arm']}` | `{zone_key(t, group)}` | `{zone}` |"
        for t in sorted(curated)
        for group, zone in curated[t]['groups'])
    return f'''# Private DNS zones

Zone keys for the dns functions, with the Private Endpoint Private DNS zone
Azure requires for each resource type group. Sourced from the
[Microsoft Learn private endpoint DNS configuration](https://learn.microsoft.com/azure/private-link/private-endpoint-dns)
appendix; type keys match the naming module's resource type keys.

| Type key | ARM resource type | Zone key | Private DNS zone |
|---|---|---|---|
{rows}
'''


def main():
    zone_map = {zone_key(t, g): z for t in CURATED for g, z in CURATED[t]['groups']}
    zones_by_type = {t: [z for _, z in CURATED[t]['groups']] for t in CURATED}
    check_against_upstream({z for z in zone_map.values()}, upstream_zones())
    with open(os.path.join(MODULE, 'zones.bicep'), 'w') as f:
        f.write(emit_zones(sorted(zone_map), zone_map, zones_by_type))
    with open(os.path.join(MODULE, 'zones.md'), 'w') as f:
        f.write(emit_zones_md(CURATED))
    print(f'emitted modules/dns/zones.bicep and zones.md ({len(zone_map)} zone keys, {len(CURATED)} type keys)')


if __name__ == '__main__':
    main()
