#!/usr/bin/env python3
"""Regenerates the naming module's generated files from upstream naming
standards:

- modules/naming/rules.bicep    - resource type keys and per-type naming rules
- modules/naming/regions.bicep  - Azure region abbreviations
- modules/naming/README.md      - API docs and catalogue

modules/naming/naming.bicep (the functions and the namingContext type) is
hand-written and imports the generated data; it is NOT generated by this
script.

Sources:
- Microsoft Azure Verified Naming Utility resource-name-rules (per-type slug,
  length, hyphen and casing rules)
  https://github.com/Azure/terraform-azure-avm-utl-naming
- claranet/terraform-azurerm-regions (region abbreviation standard)
  https://github.com/claranet/terraform-azurerm-regions

Run from the repository root: python3 scripts/generate.py
"""
import json
import os
import re
import urllib.request

AVM_BASE = 'https://raw.githubusercontent.com/Azure/terraform-azure-avm-utl-naming/main/data/'
REGIONS_URL = 'https://raw.githubusercontent.com/claranet/terraform-azurerm-regions/master/regions.tf'

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = os.path.join(REPO, 'modules', 'naming')

IDENT = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


def bicep_key(k):
    return k if IDENT.match(k) else f"'{k}'"


def distill_rules():
    generated = json.loads(fetch(AVM_BASE + 'resource-name-rules.json'))['resources']
    manual = json.loads(fetch(AVM_BASE + 'resource-name-rules.manual.json')).get('resources') or {}
    resources = dict(generated)
    for k, v in manual.items():
        resources[k] = {**resources.get(k, {}), **v}
    out = {}
    for key, r in sorted(resources.items()):
        if not r.get('slug'):
            continue
        out[key] = {
            'slug': r['slug'],
            'resourceType': r.get('resource_type'),
            'max': r.get('max_length'),
            'dashes': bool(r.get('dashes')),
            'lowercase': bool(r.get('lowercase')),
        }
    return out


def parse_locals(tf):
    """Parse HCL locals blocks of the form `  name = { key = "value" ... }`."""
    blocks = {}
    for m in re.finditer(r'^  (\w+) = \{\n(.*?)^  \}', tf, re.M | re.S):
        body = m.group(2)
        entries = re.findall(r'^\s*"?\(?([\w -]+?)\)?"?\s*=\s*"([^"]*)"\s*(?:#.*)?$', body, re.M)
        blocks[m.group(1)] = {k.strip(): v for k, v in entries}
    return blocks


def load_regions():
    blocks = parse_locals(fetch(REGIONS_URL))
    regions, short, cli = blocks['regions'], blocks['short_names'], blocks['cli_names']
    paired = blocks.get('paired', {})
    codes = {}
    rows = []
    for slug, display in regions.items():
        if slug not in short or slug not in cli or cli[slug] == slug:
            continue  # skip continental aggregates, keep real regions only
        s = short[slug]
        codes[cli[slug].lower()] = s
        codes[slug] = s
        codes[re.sub(r'\s+', '-', display.lower())] = s
        p = paired.get(slug)
        rows.append((display, cli[slug], s, short.get(p, p) if p else ''))
    return codes, rows


def emit_rules(rules):
    keys = sorted(rules)
    lines = [
        '@export()',
        "@description('Resource type identifiers supported by the naming library. Keys follow the Azure Verified Naming Utility resource catalog (https://github.com/Azure/terraform-azure-avm-utl-naming); abbreviations follow the Cloud Adoption Framework recommendations (https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations) as catalogued by the Azure Periodic Table (azureperiodictable.com); length, separator and case rules follow the Azure resource naming rules (https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules). Generated by scripts/generate.py.')",
        'type resourceType = ' + f"'{keys[0]}'",
    ]
    for k in keys[1:]:
        lines.append(f"  | '{k}'")
    lines += [
        '',
        '@export()',
        "@description('Naming rules per resource type: `slug` is the Cloud Adoption Framework abbreviation, `max` the maximum allowed name length, `dashes` whether hyphens are allowed in the name, `lowercase` whether the name must be lower case. Rules sourced from the Azure Verified Naming Utility catalog (https://github.com/Azure/terraform-azure-avm-utl-naming) and the Azure resource naming rules (https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules). Generated by scripts/generate.py.')",
        'var nameRules = {',
    ]
    for k in keys:
        r = rules[k]
        lines += [
            f'  {bicep_key(k)}: {{',
            f"    slug: '{r['slug']}'",
        ]
        if r['max'] is not None:
            lines.append(f"    max: {r['max']}")
        lines += [
            f'    dashes: {str(r["dashes"]).lower()}',
            f'    lowercase: {str(r["lowercase"]).lower()}',
            '  }',
        ]
    lines.append('}')
    return '\n'.join(lines) + '\n'


def emit_regions(region_codes):
    lines = [
        '@export()',
        "@description('Azure region abbreviations following the claranet region naming standard (https://github.com/claranet/terraform-azurerm-regions). Lookup keys accept the AZ CLI name (`uksouth`), the dashed form (`uk-south`) and the display name (`UK South`), all case insensitive; values are the short notation used as the region segment of resource names. Generated by scripts/generate.py.')",
        'var regionCodes = {',
    ]
    for k in sorted(region_codes):
        lines.append(f"  {bicep_key(k)}: '{region_codes[k]}'")
    lines.append('}')
    return '\n'.join(lines) + '\n'


def emit_readme():
    return f'''# naming

Bicep function library that composes Azure resource names which comply with the
naming rules of each resource type.

- Type abbreviations come from the
  [Cloud Adoption Framework recommendations](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations).
- Per-type rules (length, hyphens, casing) come from the
  [Azure resource naming rules](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules)
  via the [Azure Verified Naming Utility](https://github.com/Azure/terraform-azure-avm-utl-naming)
  catalog, cross-checked against the [Azure Periodic Table](https://www.azureperiodictable.com/)
  and [AZNames-bicep](https://github.com/francesco-sodano/AZNames-bicep).
- Region abbreviations follow the
  [claranet region naming standard](https://github.com/claranet/terraform-azurerm-regions).

Repository layout: `naming.bicep` holds the hand-written functions and the
`namingContext` type; `rules.bicep` (resource type keys and per-type rules),
`regions.bicep` (region abbreviations), `README.md`, `resource-types.md` and
`regions.md` are generated by `scripts/generate.py`.

## Usage

```bicep
import * as naming from 'br/ljfio:naming:0.1.0'

var segments = ['contoso', 'demo', 'uksouth', 'shared']

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {{
  name: naming.resourceName('storage_account', segments)
  // -> stcontosodemouksshared (compact + lowercase: storage forbids hyphens)
}}

resource webApp 'Microsoft.Web/sites@2023-12-01' = {{
  name: naming.resourceName('site_web_app', segments)
  // -> app-contoso-demo-uks-shared (hyphens allowed, case preserved)
}}
```

Every function takes an **array of segments** in your convention's order
(workload, environment, region, component, whatever you use). Segments are
trimmed, empty segments dropped, and any segment that names an Azure region is
abbreviated automatically (`uksouth` or `UK South` -> `uks`). The type
abbreviation is prepended automatically.

## Which segments should you use?

Follow the Cloud Adoption Framework
[naming components](https://learn.microsoft.com/azure/cloud-adoption-framework/ready/azure-best-practices/resource-naming):
`type - workload/application/project - environment - region - instance`. The
workload is the primary segment; it is what the resource belongs to.

Resist putting an organization hierarchy (organization, team, OU-like
structures) into resource names:

- **Names are permanent.** Most Azure resource names can't be changed after
  creation, and CAF's first rule is to include only information that remains
  constant. Teams and org structures reorganize; workloads don't.
- **The hierarchy is carried by scope.** Management groups and subscriptions
  model your organization; the resource group and subscription a resource sits
  in already identify the owning org and team. CAF only uses the organization
  in subscription-level names (for example `<org>-<workload>-<env>`).
- **Names have hard length limits.** Storage accounts allow 24 characters;
  every segment burns budget that the workload needs.

Capture team and other mutable ownership details in **resource tags** instead.
Keep the optional `organization` context key for its narrow legitimate use:
disambiguating globally-scoped names (storage accounts, web apps) in estates
where multiple organizations share an Azure Active Directory tenant.

## Naming context for nested modules

Define the core segments once as a context object and pass it down to nested
modules; each module then names its resources without repeating the core
segments.

```bicep
// main.bicep
param workload string = 'contoso'
param environment string = 'demo'
param location string = 'uksouth'

var namingContext = {{
  workload: workload
  environment: environment
  region: location
}}

module api 'modules/api.bicep' = {{
  name: naming.resourceNameFrom('resource_group', namingContext, ['api'])
  params: {{
    namingContext: namingContext
  }}
}}
```

```bicep
// modules/api.bicep
import * as naming from 'br/ljfio:naming:0.1.0'

param namingContext naming.namingContext

resource storageAccount 'Microsoft.Storage/storageAccounts@2023-05-01' = {{
  name: naming.resourceNameFrom('storage_account', namingContext, ['shared'])
  // -> stcontosodemouksshared
}}
```

Context keys, in this order: `organization`, `workload` (required),
`environment`, `region`, `component` - all but `workload` optional. The context
type is sealed, so typos fail at build time; pass additional segments via
`extraSegments` (which may be null). `segmentsFrom(context)` returns the ordered
segment array when you need it directly.

## Exported types

| Type | Description |
|---|---|
| `resourceType` | Union of all supported resource type keys (the first parameter of every naming function). |
| `namingContext` | Sealed object type with the `organization`, `workload` (required), `environment`, `region`, `component` (optional) keys; type your nested module parameters with it. |

## Functions

| Function | Description |
|---|---|
| `resourceName(type, segments string[])` | Compliant name for the type: hyphens when allowed, compact when not, lower case when required, truncated to the type's maximum length. |
| `compactResourceName(type, segments string[])` | Same, but always compact (hyphens stripped). |
| `resourceNameFrom(type, context namingContext, extraSegments string[]?)` | As `resourceName`, building the leading segments from a naming context object; `extraSegments` (null or empty for none) are appended after the context segments. |
| `segmentsFrom(context namingContext)` | Ordered segments for a naming context object (`organization`, required `workload`, optional `environment`, `region`, `component`; region abbreviated). |
| `resourceAbbreviation(type)` | The Cloud Adoption Framework abbreviation for the type (`resource_group` -> `rg`). |
| `regionCode(region)` | Short abbreviation for an Azure region (`westeurope`/`West Europe` -> `euw`); unknown values pass through unchanged. |
| `resourceNameMaxLength(type)` | Maximum name length allowed for the type (255 when undocumented). |

## Why not `naming.resource.storageAccount(...)`?

Bicep user-defined functions cannot be grouped into nested namespaces, so
`naming.resource.storageAccount(...)` is not expressible. Generating one
exported function per resource type is also not viable: Bicep inlines every
exported function into each consuming template (a consumer using 2 of 300
exported functions receives all 301), so 579 per-type wrappers would far exceed
ARM's per-template function limits and bloat every deployment. Use
`resourceName('<type key>', segments)` with the type key table below instead.

## Compliance behaviour

- Types that forbid hyphens (storage accounts, Analysis Services, ...) are
  joined without a separator automatically; types that allow them are joined
  with `-`.
- Types that require lower case (storage accounts, ...) are lower cased
  automatically.
- Names longer than the type's documented maximum are truncated from the end.
  Keep segments short; truncation is deterministic but can make two long names
  collide.

## Region abbreviations

The full region table, including AZ CLI names and paired regions, is in
[regions.md](regions.md).

## Supported resource types

The full catalogue of type keys, abbreviations and naming rules is in
[resource-types.md](resource-types.md).
'''


def emit_resource_types_md(rules):
    keys = sorted(rules)
    rows = '\n'.join(
        f"| `{k}` | {rules[k]['resourceType'] or ''} | `{rules[k]['slug']}` | "
        f"{rules[k]['max'] if rules[k]['max'] is not None else '&mdash;'} | "
        f"{'yes' if rules[k]['dashes'] else 'no'} | {'yes' if rules[k]['lowercase'] else 'no'} |"
        for k in keys)
    return f'''# Supported resource types

Type keys for the naming functions, with the Cloud Adoption Framework
abbreviation and the per-type naming rules used to compose compliant names.
Sourced from the [Azure Verified Naming Utility](https://github.com/Azure/terraform-azure-avm-utl-naming)
catalog and the [Azure resource naming rules](https://learn.microsoft.com/azure/azure-resource-manager/management/resource-name-rules).

| Type key | ARM resource type | Abbreviation | Max length | Hyphens | Lower case |
|---|---|---|---|---|---|
{rows}
'''


def emit_regions_md(region_rows):
    rows = '\n'.join(
        f'| {display} | `{cli}` | `{short}` | {paired} |' for display, cli, short, paired in region_rows)
    return f'''# Region abbreviations

Azure region abbreviations following the
[claranet region naming standard](https://github.com/claranet/terraform-azurerm-regions).
The naming functions accept the AZ CLI name, the dashed form or the display
name as the region segment (for example `uksouth`, `uk-south` or `UK South`),
all case insensitive.

| Region | AZ CLI name | Abbreviation | Paired region |
|---|---|---|---|
{rows}
'''


def main():
    rules = distill_rules()
    region_codes, region_rows = load_regions()
    print(f'{len(rules)} resource types, {len(region_codes)} region lookup keys, {len(region_rows)} regions')
    with open(os.path.join(MODULE, 'rules.bicep'), 'w') as f:
        f.write(emit_rules(rules))
    with open(os.path.join(MODULE, 'regions.bicep'), 'w') as f:
        f.write(emit_regions(region_codes))
    with open(os.path.join(MODULE, 'README.md'), 'w') as f:
        f.write(emit_readme())
    with open(os.path.join(MODULE, 'resource-types.md'), 'w') as f:
        f.write(emit_resource_types_md(rules))
    with open(os.path.join(MODULE, 'regions.md'), 'w') as f:
        f.write(emit_regions_md(region_rows))
    print('emitted modules/naming/rules.bicep, regions.bicep, README.md, resource-types.md and regions.md')


if __name__ == '__main__':
    main()
