#!/usr/bin/env python3
"""Regenerates the ids module's generated files:

- modules/ids/types.bicep        - resource type keys and their ARM provider types
- modules/ids/resource-types.md  - resource type catalogue

modules/ids/ids.bicep (the ID builder functions) and modules/ids/README.md
(the API and usage docs) are hand-written and are NOT generated by this
script; ids.bicep imports the generated data.

The type-key vocabulary is curated in TYPES below (embedded, not fetched):
the most common top-level Azure resource types, with keys aligned with the
naming module's catalogue. Every curated provider type string is verified at
generation time:

- against the Microsoft Learn ARM reference (https://learn.microsoft.com/azure/templates/):
  the per-type page must exist (a 404 means the type is not in the reference)
  and its title must use exactly the curated casing;
- against the Azure Verified Naming Utility resource-name-rules catalog
  (https://github.com/Azure/terraform-azure-avm-utl-naming) that the naming
  module derives its keys and abbreviations from: each key must exist there
  and its resource_type must match the curated value (case insensitive),
  except for the entries listed in AVM_OVERRIDES.

Run from the repository root: python3 scripts/generate_ids.py
"""
import json
import os
import re
import sys
import urllib.error
import urllib.request

AVM_BASE = 'https://raw.githubusercontent.com/Azure/terraform-azure-avm-utl-naming/main/data/'
LEARN_TEMPLATES = 'https://learn.microsoft.com/en-us/azure/templates/'

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MODULE = os.path.join(REPO, 'modules', 'ids')

IDENT = re.compile(r'^[a-zA-Z_][a-zA-Z0-9_]*$')

# Curated: naming-style type key -> ARM resource provider type. Keys follow
# the naming module's catalogue wherever the type is covered there, so the
# same key names a resource with naming.resourceName and identifies it with
# the ids functions. Only top-level resource types are included: types whose
# ID is /subscriptions/<sub>/resourceGroups/<rg>/providers/<type>/<name>.
TYPES = {
    'account_open_ai': 'Microsoft.CognitiveServices/accounts',
    'action_group': 'Microsoft.Insights/actionGroups',
    'api_management_service': 'Microsoft.ApiManagement/service',
    'application_gateway': 'Microsoft.Network/applicationGateways',
    'automation_account': 'Microsoft.Automation/automationAccounts',
    'availability_set': 'Microsoft.Compute/availabilitySets',
    'azure_firewall': 'Microsoft.Network/azureFirewalls',
    'bastion_host': 'Microsoft.Network/bastionHosts',
    'batch_account': 'Microsoft.Batch/batchAccounts',
    'component': 'Microsoft.Insights/components',
    'compute_virtual_machine': 'Microsoft.Compute/virtualMachines',
    'configuration_store': 'Microsoft.AppConfiguration/configurationStores',
    'container_app': 'Microsoft.App/containerApps',
    'container_group': 'Microsoft.ContainerInstance/containerGroups',
    'container_service_managed_cluster': 'Microsoft.ContainerService/managedClusters',
    'database_account': 'Microsoft.DocumentDB/databaseAccounts',
    'databricks_workspace': 'Microsoft.Databricks/workspaces',
    'db_for_my_sql_server': 'Microsoft.DBforMySQL/flexibleServers',
    'db_for_postgre_sql_server': 'Microsoft.DBforPostgreSQL/flexibleServers',
    'disk': 'Microsoft.Compute/disks',
    'dns_zone': 'Microsoft.Network/dnsZones',
    'event_hub_namespace': 'Microsoft.EventHub/namespaces',
    'factory': 'Microsoft.DataFactory/factories',
    'hosting_environment_app_service_environment': 'Microsoft.Web/hostingEnvironments',
    'iot_hub': 'Microsoft.Devices/IotHubs',
    'key_vault_vault': 'Microsoft.KeyVault/vaults',
    'load_balancer': 'Microsoft.Network/loadBalancers',
    'machine_learning_workspace': 'Microsoft.MachineLearning/workspaces',
    'managed_environment': 'Microsoft.App/managedEnvironments',
    'managed_hsm': 'Microsoft.KeyVault/managedHSMs',
    'managed_instance': 'Microsoft.Sql/managedInstances',
    'network_interface': 'Microsoft.Network/networkInterfaces',
    'network_security_group': 'Microsoft.Network/networkSecurityGroups',
    'operational_insights_workspace': 'Microsoft.OperationalInsights/workspaces',
    'private_dns_zone': 'Microsoft.Network/privateDnsZones',
    'private_endpoint': 'Microsoft.Network/privateEndpoints',
    'proximity_placement_group': 'Microsoft.Compute/proximityPlacementGroups',
    'public_ip_address': 'Microsoft.Network/publicIPAddresses',
    'purview_account': 'Microsoft.Purview/accounts',
    'recovery_services_vault': 'Microsoft.RecoveryServices/vaults',
    'redis': 'Microsoft.Cache/redis',
    'registry': 'Microsoft.ContainerRegistry/registries',
    'resource_group': 'Microsoft.Resources/resourceGroups',
    'route_table': 'Microsoft.Network/routeTables',
    'search_service': 'Microsoft.Search/searchServices',
    'server_farm': 'Microsoft.Web/serverfarms',
    'service_bus_namespace': 'Microsoft.ServiceBus/namespaces',
    'site_function_app': 'Microsoft.Web/sites',
    'site_web_app': 'Microsoft.Web/sites',
    'sql_server': 'Microsoft.Sql/servers',
    'ssh_public_key': 'Microsoft.Compute/sshPublicKeys',
    'static_site': 'Microsoft.Web/staticSites',
    'storage_account': 'Microsoft.Storage/storageAccounts',
    'synapse_workspace': 'Microsoft.Synapse/workspaces',
    'topic': 'Microsoft.EventGrid/topics',
    'traffic_manager_profile': 'Microsoft.Network/trafficmanagerprofiles',
    'user_assigned_identity': 'Microsoft.ManagedIdentity/userAssignedIdentities',
    'virtual_machine_scale_set': 'Microsoft.Compute/virtualMachineScaleSets',
    'virtual_network': 'Microsoft.Network/virtualNetworks',
    'virtual_network_gateway': 'Microsoft.Network/virtualNetworkGateways',
}

# Keys that deliberately differ from the naming catalog's resource_type: the
# AVM naming catalog lists the retired single-server database types
# (Microsoft.DBforMySQL/servers, Microsoft.DBforPostgreSQL/servers); these
# entries map the same naming keys to the flexible server types, which are
# the only types deployable for new databases.
AVM_OVERRIDES = {
    'db_for_my_sql_server': 'Microsoft.DBforMySQL/flexibleServers',
    'db_for_postgre_sql_server': 'Microsoft.DBforPostgreSQL/flexibleServers',
}


def fetch(url):
    with urllib.request.urlopen(url) as r:
        return r.read().decode()


def bicep_key(k):
    return k if IDENT.match(k) else f"'{k}'"


def learn_canonical(arm_type):
    """Return the canonical provider/type casing from the Microsoft Learn ARM
    reference page for the type; raise when the page does not exist."""
    provider, _, type_name = arm_type.partition('/')
    url = f'{LEARN_TEMPLATES}{provider.lower()}/{type_name.lower()}'
    try:
        page = fetch(url)
    except urllib.error.HTTPError as e:
        raise RuntimeError(f'not in the Microsoft Learn ARM reference ({e.code}): {url}') from e
    m = re.search(r'<title>([^<]*)</title>', page)
    if not m:
        raise RuntimeError(f'no reference page title at {url}')
    return m.group(1).split(' - ')[0]


def verify_types():
    generated = json.loads(fetch(AVM_BASE + 'resource-name-rules.json'))['resources']
    manual = json.loads(fetch(AVM_BASE + 'resource-name-rules.manual.json')).get('resources') or {}
    resources = dict(generated)
    for k, v in manual.items():
        resources[k] = {**resources.get(k, {}), **v}

    problems = []
    for key, arm_type in sorted(TYPES.items()):
        expected = AVM_OVERRIDES.get(key, arm_type)
        if key not in resources:
            problems.append(f'{key}: not in the naming catalog the key vocabulary is aligned with')
        elif key not in AVM_OVERRIDES:
            avm = resources[key].get('resource_type')
            if avm and avm.lower() != expected.lower():
                problems.append(f'{key}: naming catalog says {avm}, curated value is {expected}')
        try:
            canonical = learn_canonical(arm_type)
        except RuntimeError as e:
            problems.append(f'{key}: {e}')
            continue
        if canonical != arm_type:
            problems.append(f'{key}: curated {arm_type} does not match the Microsoft Learn '
                            f'canonical casing {canonical}')
    if problems:
        for p in problems:
            print(f'ERROR {p}', file=sys.stderr)
        sys.exit(f'{len(problems)} curated type(s) failed verification')
    return {k: resources[k].get('slug') for k in TYPES}


def emit_types():
    keys = sorted(TYPES)
    lines = [
        '@export()',
        "@description('Resource type identifiers supported by the ids library. Keys follow the naming module type keys (the Azure Verified Naming Utility resource catalog, https://github.com/Azure/terraform-azure-avm-utl-naming), so the same key that names a resource with the naming functions identifies it with the ids functions. Generated by scripts/generate_ids.py.')",
        'type idType = ' + f"'{keys[0]}'",
    ]
    for k in keys[1:]:
        lines.append(f"  | '{k}'")
    lines += [
        '',
        '@export()',
        "@description('ARM resource provider type per type key, casing verified against the Microsoft Learn ARM reference (https://learn.microsoft.com/azure/templates/). Generated by scripts/generate_ids.py.')",
        'var providerTypes = {',
    ]
    for k in keys:
        lines.append(f"  {bicep_key(k)}: '{TYPES[k]}'")
    lines.append('}')
    return '\n'.join(lines) + '\n'


def emit_resource_types_md(slugs):
    rows = '\n'.join(
        f"| `{k}` | `{TYPES[k]}` | `{slugs[k] or ''}` |" for k in sorted(TYPES))
    return f'''# Supported resource types

Type keys for the ids functions with their ARM resource provider types.
Keys follow the [naming module](../naming/README.md)'s catalogue, so the same
key names a resource with the naming functions and identifies it with the ids
functions. Provider type strings are verified against the
[Microsoft Learn ARM reference](https://learn.microsoft.com/azure/templates/).
Only top-level resource types are included: types whose ID is
`/subscriptions/<sub>/resourceGroups/<rg>/providers/<type>/<name>`.

| Type key | ARM resource type | Naming abbreviation |
|---|---|---|
{rows}
'''


def main():
    slugs = verify_types()
    print(f'{len(TYPES)} resource types verified')
    with open(os.path.join(MODULE, 'types.bicep'), 'w') as f:
        f.write(emit_types())
    with open(os.path.join(MODULE, 'resource-types.md'), 'w') as f:
        f.write(emit_resource_types_md(slugs))
    print('emitted modules/ids/types.bicep and resource-types.md')


if __name__ == '__main__':
    main()
